### ISSUE TITLE
Adding another option to download the app

### ISSUE THREAD

**Issue by reysetti** [Jomme5/AddressToGPSII#2]
I honestly do not care that your charging for the app but a lot of the reason people look for an app like this is because the use osmand as a replacement for Google Maps. For me i do not have anything Google related on my phone. If you could add another option where I can pay you and I can download the app that would be great.

**Comment by Jomme5** [comment]
Sorry for my late answer. Didn't got any e-mail-notification... :( Normally most people have google-playstore on their phones. In case your phone is rooted and you threw off the google-playstore-service(if some apps are still be able to work anyways?), I can send you a copy.  Notice that the underlying service of the app is not longer Bing, but Google.
